### ISSUE TITLE
Use SHA256 or SHA512

### ISSUE THREAD

**Issue by MarcoSteinke** [FirelandsProject/firelands-cata#108]
https://github.com/FirelandsProject/firelands-cata/blob/f01ddc2a0bde0df8d36428979d763c4b3cc6e443/src/server/game/Accounts/AccountMgr.cpp#L381

The given line of code uses SHA1 to hash the password of a newly registered account. The SHA1 hash function is not able to guarantee security any longer, as a lot of different sources explain.

## Fix:

You can fix this security risk by replacing the usage of SHA1 with for example SHA256 or other secure hash functions.

## Risks:

Servers, which are deployed using the `firelands-cata` codebase could face attacks in which attackers could comprimise accounts of admins and thus damage the server.

## Sources:

- https://www.computerworld.com/article/3173616/the-sha1-hash-function-is-now-completely-unsafe.html
- https://crypto.stackexchange.com/questions/48289/how-secure-is-sha1-what-are-the-chances-of-a-real-exploit
- https://en.wikipedia.org/wiki/SHA-1

**Comment by seobryn** [comment]
Hi Marco, thanks for the Feedback, We will take this into account to fix as soon as possible!

**Comment by seobryn** [comment]
Sorry for the late reponse, but Im reviewing about the issue, and Is not necessary to Upgrade to SHA256 because We are using SRP6 Protocol for Authentication, so The possibilities to break the password are really slow because SRP6 always generate a different key pairs for authentication, so The possibilities to break the password are once per try.
