### ISSUE TITLE
I Can't Wear This - Quest: 14400

### ISSUE THREAD

**Issue by seobryn** [FirelandsProject/firelands-cata#31]
### Current Behaviour

https://medal.tv/games/requested/clips/y4d3gK5J520ef/d13370HgsaMO?invite=cr-MSw4aEYsODUwNjEzMTEs

### Expected Blizzlike Behaviour

https://www.wowhead.com/quest=14400/i-cant-wear-this#videos:id=34378

### Steps to reproduce the problem

1. Start quest chain https://www.wowhead.com/quest=14398/grandma-wahl
2. Complete until wowhead.com/quest=14400/i-cant-wear-this
3. Try to do this quest

### FC rev. hash/commit

Firelands rev. 4b8cd91efa90 2022-08-25 12:02:21 -0500 (master branch)

### Operating system

Mac OSX

**Comment by pangolp** [comment]
```sql
-- Default: 181
UPDATE `gameobject` SET `PhaseId`=183 WHERE `guid`=236357;
```
I am not 100% sure, if we have to do that, however, that is the phase of the NPC that gives you the quest, I do not understand why the object, has a different phase, the problem is that so far, I could not get information on whether or not it is the correct phase. So this can be solved, however, I don't know if it is correct to do so.

![WoWScrnShot_082722_061238](https://user-images.githubusercontent.com/2810187/187023679-161d18c8-3631-4560-86d7-b8153c59b6cc.jpg)

Any opinion on this matter? @Meltie2013

**Comment by pangolp** [comment]
In the end, he scrambles with conditionals.
One less thing to learn.

**Comment by Meltie2013** [comment]
I think the phaseId is a sniff value, since that starting zone is complex.

**Comment by pangolp** [comment]
> I think the phaseId is a sniff value, since that starting zone is complex.

Yes, it is complex, but for the moment, I think we will have to settle for the pull request that was created, until we find another way to do it (if it exists). For the moment, I think the pull request responds well, although I didn't test it.
